"""Windows binary packaging and InnoSetup installer generation."""

from pathlib import Path
import sys
from typing import List, Optional, Union

from neron.packaging.config import PackagingConfig
from neron.packaging.spec import PyInstallerSpecGenerator
from neron.utils.logger import get_logger

logger = get_logger("packaging.windows")


class WindowsPackager:
    """
    Handles Windows executable building via PyInstaller and generates
    InnoSetup installation scripts for distribution.
    """

    @classmethod
    def generate_inno_setup_script(
        cls,
        config: PackagingConfig,
        dist_dir: Optional[Union[str, Path]] = None,
    ) -> str:
        """
        Generate a complete InnoSetup (.iss) script for building a Windows installer.
        """
        dist_path = Path(dist_dir).resolve() if dist_dir else Path("dist/neron").resolve()
        dist_repr = str(dist_path).replace("/", "\\")

        iss_script = f'''; Inno Setup Script for {config.app_name}
; Generated by Neron Packaging Engine

#define MyAppName "{config.app_name}"
#define MyAppVersion "{config.version}"
#define MyAppPublisher "{config.author}"
#define MyAppExeName "{config.app_name.lower()}.exe"

[Setup]
AppId={{{{A84B96F3-9D11-4E84-884E-F4D32A1C9081}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir=.
OutputBaseFilename={config.app_name}-Setup-v{config.version}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{dist_repr}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent
'''
        return iss_script

    @classmethod
    def write_inno_setup_file(
        cls,
        config: PackagingConfig,
        output_file: Union[str, Path],
        dist_dir: Optional[Union[str, Path]] = None,
    ) -> Path:
        out_path = Path(output_file).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        content = cls.generate_inno_setup_script(config, dist_dir=dist_dir)
        out_path.write_text(content, encoding="utf-8")
        logger.info(f"Generated InnoSetup script at: {out_path}")
        return out_path

    @classmethod
    def get_pyinstaller_build_command(
        cls,
        spec_file: Union[str, Path],
        dist_dir: Optional[Union[str, Path]] = None,
    ) -> List[str]:
        """Generate command arguments to execute PyInstaller."""
        spec_path = Path(spec_file).resolve()
        cmd = [sys.executable, "-m", "PyInstaller", str(spec_path), "--noconfirm"]
        if dist_dir:
            cmd.extend(["--distpath", str(Path(dist_dir).resolve())])
        return cmd
